### ISSUE TITLE
Building Project Fails

### ISSUE THREAD

**Issue by jinder** [NathanWalker/ng2-image-lazy-load#16]
I was attempting to do a PR to change the behaviour of the component so that it detects the first scrollable parent element rather than attaching to window scroll.  However, I can't seem to get the project to build.  Doing 'npm run build' on Node 6.7 results in:

```
bash-3.2$ npm run build                                                                                           

> ng2-image-lazy-load@2.0.8 build /Users/jinder/git/ng2-image-lazy-load                                           
> rimraf dist && webpack --progress --profile --bail                                                              

 50% 2/3 build modulesError: Emit skipped Error: Emit skipped                                                     
    at State.emit (/Users/jinder/git/ng2-image-lazy-load/node_modules/awesome-typescript-loader/src/host.ts:254:19
)                                                                                                                 
    at transform (/Users/jinder/git/ng2-image-lazy-load/node_modules/awesome-typescript-loader/src/index.ts:147:28
)                                                                                                                 
    at transformationFunction (/Users/jinder/git/ng2-image-lazy-load/node_modules/awesome-typescript-loader/src/in
dex.ts:89:48)                                                                                                     
    at compiler (/Users/jinder/git/ng2-image-lazy-load/node_modules/awesome-typescript-loader/src/index.ts:105:34)
    at Object.loader (/Users/jinder/git/ng2-image-lazy-load/node_modules/awesome-typescript-loader/src/index.ts:18
:18)                                                                          
at Object.loader (/Users/jinder/git/ng2-image-lazy-load/node_modules/awesome-typescript-loader/src/index.ts:18
:18)                                                                                                              
    at WEBPACK_CORE_LOADER_EXECUTION (/Users/jinder/git/ng2-image-lazy-load/node_modules/webpack-core/lib/NormalMo
duleMixin.js:155:71)                                                                                              
    at runSyncOrAsync (/Users/jinder/git/ng2-image-lazy-load/node_modules/webpack-core/lib/NormalModuleMixin.js:15
5:93)                                                                                                             
    at nextLoader (/Users/jinder/git/ng2-image-lazy-load/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /Users/jinder/git/ng2-image-lazy-load/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15            
    at Object.context.callback (/Users/jinder/git/ng2-image-lazy-load/node_modules/webpack-core/lib/NormalModuleMi
xin.js:148:14)                                                                                                    
    at Object.module.exports (/Users/jinder/git/ng2-image-lazy-load/node_modules/angular2-template-loader/index.js
:32:10)                                                                                                           
    at WEBPACK_CORE_LOADER_EXECUTION (/Users/jinder/git/ng2-image-lazy-load/node_modules/webpack-core/lib/NormalMo
duleMixin.js:155:71)  
```

Any ideas?

**Comment by NathanWalker** [comment]
Thanks @jinder just got back in town, and seeing this as well.
May be an update to the webpack build, I'll see if I can get it working tomorrow.

**Comment by NathanWalker** [comment]
@jinder Went ahead and updated a couple things and got the dev build server working again.
Thanks for any future contribution!
